:title: All about pages
:body: |
  Each page is stored in its own directory, it uses a `.yml` file to hold its textual content. 
  That same `.yml` file is also used to infer the template that will be used for your page. For example, `default.yml` will use the `default.mustache` template.
  
  Pages have variables for meta information, also, the key and value pairs in the `.yml` file will be cast to variables.
  For example:

      content/
        index/
          default.yml
  The index page will use the `default.mustache` template

  #### Page variables
  
  | Variable  | What it does |  
  |:----------|:-------------|
  |children   | All of the non-floating pages underneath the current page |
  |siblings   | All of the non-floating pages at the same level. Does not include 'self' |
  |ancestors  | Each parent up the tree - Useful for breadcrumbing |
  |parent     | The direct parent page |
  |permalink  | The full routable path to the page, eg: `/about/our/services` |
  |slug       | The last chunk of a page name, can be used in HTML as an ID or className, eg: `services` |
  |name       | A titlcased version of the slug. This can be useful for use in navigation or links |
  |navigation | The top level non-floating pages |
  
  #### "Magic" variables
  A page that contains subdirectories will receive additional variables, for example:
    
      content/
        index/
          default.yml
          images/
            sansei.jpg
            miaggi.jpg
  The index page will have an array variable of `images`, it will contain a hash:
    
      [
        {
          :name => "sansei.jpg", 
          :path => "/index/images/sansei.jpg", 
          :disk_path => ".../bonsai-site/content/index/images/sansei.jpg"
        },
        {
          :name => "miaggi.jpg", 
          :path => "/index/images/miaggi.jpg", 
          :disk_path => ".../bonsai-site/content/index/images/miaggi.jpg"
        }
      ]
